quarkus.http.port=8080
quarkus.datasource.db-kind=postgresql
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/postgres
quarkus.datasource.jdbc.driver=org.postgresql.Driver
quarkus.datasource.jdbc.max-size=8
quarkus.datasource.jdbc.min-size=2
quarkus.datasource.username=postgres
quarkus.datasource.password=postgres

quarkus.flyway.active=true
quarkus.flyway.locations=classpath:db/migrations
quarkus.flyway.default-schema=public
quarkus.flyway.baseline-on-migrate=true
quarkus.flyway.jdbc-url=jdbc:postgresql://localhost:5432/postgres
quarkus.flyway.username=postgres
quarkus.flyway.password=postgres
